Update main.css
cividi/spatial-data-package-platform pull request #42
Opened 2021-01-21 22:25 UTC by loleg

Hide unnecessary vertical overflow scrollbars from appearing, which looks to be more of an issue on Webkit.

![Screenshot from 2021-01-21 23-24-40](https://user-images.githubusercontent.com/31819/105419978-dd465080-5c3f-11eb-8002-2acf26da7537.png)

2021-01-21 23:03 UTC, n0rdlicht requested changes
Also results in disabled scrollbars and scrolling for static content pages.

2021-01-22 08:21 UTC, loleg commented
Oops! Then I need to be pointed to the right bit of CSS for map views.

2021-01-27 16:16 UTC, n0rdlicht commented
@loleg do you see an existing CSS scope to add this too or should we consider adding this to the UX/UI revision list in #47?

2021-01-28 13:30 UTC, loleg commented
Sounds like there's potential upstream impact. Let's come back to this as you suggested.

2021-01-28 13:30 UTC, closed without merging